// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OmuzgorServise.Data;

#nullable disable

namespace OmuzgorServise.Migrations
{
    [DbContext(typeof(OmuzgorDbContext))]
    [Migration("20251028085531_AddOmuzgorTable")]
    partial class AddOmuzgorTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OmuzgorServise.Model.Daraja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nomgu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sharh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Daraja");
                });

            modelBuilder.Entity("OmuzgorServise.Model.Omuzgor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdDaraja")
                        .HasColumnType("integer");

                    b.Property<int>("IdUnvon")
                        .HasColumnType("integer");

                    b.Property<string>("JoiTav")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JoiZist")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Pol")
                        .HasColumnType("integer");

                    b.Property<string>("Rasm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telephon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdDaraja");

                    b.HasIndex("IdUnvon");

                    b.ToTable("Omuzgoron");
                });

            modelBuilder.Entity("OmuzgorServise.Model.Unvon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nomgu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sharh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Unvon");
                });

            modelBuilder.Entity("OmuzgorServise.Model.Omuzgor", b =>
                {
                    b.HasOne("OmuzgorServise.Model.Daraja", "Daraja")
                        .WithMany("Omuzgoron")
                        .HasForeignKey("IdDaraja")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmuzgorServise.Model.Unvon", "Unvon")
                        .WithMany("Omuzgoron")
                        .HasForeignKey("IdUnvon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Daraja");

                    b.Navigation("Unvon");
                });

            modelBuilder.Entity("OmuzgorServise.Model.Daraja", b =>
                {
                    b.Navigation("Omuzgoron");
                });

            modelBuilder.Entity("OmuzgorServise.Model.Unvon", b =>
                {
                    b.Navigation("Omuzgoron");
                });
#pragma warning restore 612, 618
        }
    }
}
